//! `SetConsoleCtrlHandler` — Windows' console-control-event mechanism, the
//! closest analog to `SIGINT`/`SIGTERM`/`SIGHUP` delivery for a console app.
//! Not a signal mask or `sigaction`-alike: handlers run on a dedicated
//! system-created thread, in one process-wide chain (`TRUE`/`FALSE` in
//! `SetConsoleCtrlHandler`'s second argument pushes/pops one entry), and
//! only `CTRL_C_EVENT`/`CTRL_BREAK_EVENT` are events a console app can
//! itself *generate*; `CTRL_CLOSE_EVENT`/`CTRL_LOGOFF_EVENT`/
//! `CTRL_SHUTDOWN_EVENT` are host-delivered shutdown notifications with no
//! Unix signal-number equivalent at all. See rush's
//! `docs/WINDOWS_BACKEND_ANALYSIS.md` §4.4 for the motivating case this
//! module exists for: a `trap 'cmd' TERM` that's silently accepted on
//! Windows today but has nothing installed to ever fire it.

use crate::error::Win32Error;
use crate::handle::RawHandle;

/// Ctrl+C, generated by the console driver (roughly `SIGINT`).
pub const CTRL_C_EVENT: u32 = 0;
/// Ctrl+Break — no Unix keystroke maps to this one.
pub const CTRL_BREAK_EVENT: u32 = 1;
/// The console window is closing (no exact Unix analog; closest in spirit
/// to `SIGHUP`).
pub const CTRL_CLOSE_EVENT: u32 = 2;
/// The current user is logging off (no Unix analog).
pub const CTRL_LOGOFF_EVENT: u32 = 5;
/// The system is shutting down (closest in spirit to `SIGTERM`).
pub const CTRL_SHUTDOWN_EVENT: u32 = 6;

/// A console control handler: called on a dedicated system thread with one
/// of the `CTRL_*_EVENT` constants above. Return nonzero (`TRUE`) to claim
/// the event — stopping it from propagating to the next handler in the
/// chain, or to the default handler, which terminates the process for every
/// event this module defines; return `0` (`FALSE`) to let it fall through.
///
/// `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, and `CTRL_SHUTDOWN_EVENT`
/// handlers get a bounded time budget before Windows kills the process
/// regardless (a few seconds) — keep the handler itself to the same "store
/// an atomic, do nothing else" pattern rush's own `trap::record_signal`
/// already uses for `SIGTERM`/`SIGHUP` on Unix, and let ordinary code pick
/// the stored value up at a safe point afterward.
pub type HandlerRoutine = extern "system" fn(ctrl_type: u32) -> i32;

#[link(name = "kernel32")]
unsafe extern "system" {
    fn SetConsoleCtrlHandler(handler_routine: Option<HandlerRoutine>, add: i32) -> i32;
    fn GetConsoleMode(console_handle: RawHandle, mode: *mut u32) -> i32;
    fn SetConsoleMode(console_handle: RawHandle, mode: u32) -> i32;
    fn ReadFile(
        file: RawHandle,
        buffer: *mut u8,
        bytes_to_read: u32,
        bytes_read: *mut u32,
        overlapped: *mut core::ffi::c_void,
    ) -> i32;
    fn GetConsoleScreenBufferInfo(
        console_output: RawHandle,
        buffer_info: *mut ConsoleScreenBufferInfo,
    ) -> i32;
    fn WaitForSingleObject(handle: RawHandle, milliseconds: u32) -> u32;
}

const WAIT_OBJECT_0: u32 = 0;
const WAIT_TIMEOUT: u32 = 258;

// Console input-mode bits (`GetConsoleMode`/`SetConsoleMode` on an input
// handle). What "raw mode" means in terms of these — which bits to clear
// or set — is deliberately *not* decided here, the same way `rusty_libc`
// exposes `tcgetattr`/`tcsetattr` without baking in a raw-mode recipe:
// that policy belongs to the line-editor consumer (`rusty_lines`'
// `term_sys.rs` on Unix), not this crate.
/// Ctrl+C/Ctrl-Break are intercepted and converted to the corresponding
/// `CTRL_*_EVENT` (via [`install_ctrl_handler`]) rather than delivered as
/// input — set by default. Clearing this is what lets a raw-mode reader see
/// Ctrl+C as ordinary input instead of the OS terminating the process.
pub const ENABLE_PROCESSED_INPUT: u32 = 0x0001;
/// Line-buffered input: `ReadFile`/`ReadConsole` doesn't return until a
/// carriage return, and backspace/editing happens in the console host
/// itself — set by default. The Windows analog of `ICANON`; clear it for
/// the same reason a Unix raw-mode setup clears `ICANON`.
pub const ENABLE_LINE_INPUT: u32 = 0x0002;
/// The console host echoes typed characters — set by default, only
/// meaningful with `ENABLE_LINE_INPUT` also set. The Windows analog of
/// `ECHO`.
pub const ENABLE_ECHO_INPUT: u32 = 0x0004;
/// `WINDOW_BUFFER_SIZE_EVENT` input records are generated on resize.
pub const ENABLE_WINDOW_INPUT: u32 = 0x0008;
/// Mouse events are reported as input records.
pub const ENABLE_MOUSE_INPUT: u32 = 0x0010;
pub const ENABLE_INSERT_MODE: u32 = 0x0020;
/// Mouse/keyboard input is consumed by the console's own Quick Edit
/// selection UI rather than delivered to the application — usually wanted
/// off for a raw-mode reader for the same reason it's wanted off for any
/// full-screen or line-editing console app.
pub const ENABLE_QUICK_EDIT_MODE: u32 = 0x0040;
/// Must be set for `ENABLE_INSERT_MODE`/`ENABLE_QUICK_EDIT_MODE` to have
/// any effect — a documented Windows quirk, not a real feature of its own.
pub const ENABLE_EXTENDED_FLAGS: u32 = 0x0080;
/// `ReadFile`/`ReadConsole` on this input handle delivers a VT/ANSI escape
/// byte stream for special keys (arrows, function keys, …) instead of
/// requiring `ReadConsoleInputW`'s structured `INPUT_RECORD`s — the single
/// bit that makes a Windows 10+ console behave like a Unix tty for input
/// purposes, and the reason this crate's Windows floor (10 1809+) is new
/// enough to support it at all.
pub const ENABLE_VIRTUAL_TERMINAL_INPUT: u32 = 0x0200;

// Console output-mode bits (`GetConsoleMode`/`SetConsoleMode` on an output
// handle).
pub const ENABLE_PROCESSED_OUTPUT: u32 = 0x0001;
pub const ENABLE_WRAP_AT_EOL_OUTPUT: u32 = 0x0002;
/// VT/ANSI escape sequences written to this output handle are interpreted
/// (cursor movement, colors, …) instead of printed literally — the output
/// counterpart of `ENABLE_VIRTUAL_TERMINAL_INPUT`, needed for the same
/// repaint escape sequences a Unix terminal already understands by default.
pub const ENABLE_VIRTUAL_TERMINAL_PROCESSING: u32 = 0x0004;
/// A bare `\n` moves down without returning to column 0 — matching how a
/// Unix terminal's `\n` behaves once `ONLCR`-style translation is off,
/// needed so a VT-aware repaint (which sends its own `\r` where it means
/// it) doesn't get an extra implicit carriage return.
pub const DISABLE_NEWLINE_AUTO_RETURN: u32 = 0x0008;

// CONSOLE_SCREEN_BUFFER_INFO (and its COORD/SMALL_RECT members): `size_of`
// 22, `align_of` 2 on x86_64. Verified against mingw-w64's `wincon.h` the
// same way as `process.rs`/`job.rs`'s structs (a `_Static_assert` probe
// compiled with `x86_64-w64-mingw32-gcc` against the real header).
#[repr(C)]
#[derive(Default, Clone, Copy)]
struct Coord {
    x: i16,
    y: i16,
}

#[repr(C)]
#[derive(Default, Clone, Copy)]
struct SmallRect {
    left: i16,
    top: i16,
    right: i16,
    bottom: i16,
}

#[repr(C)]
#[derive(Default, Clone, Copy)]
struct ConsoleScreenBufferInfo {
    size: Coord,
    cursor_position: Coord,
    attributes: u16,
    window: SmallRect,
    maximum_window_size: Coord,
}
const _: () = assert!(core::mem::size_of::<ConsoleScreenBufferInfo>() == 22);
const _: () = assert!(core::mem::align_of::<ConsoleScreenBufferInfo>() == 2);

/// Push `handler` onto the process-wide console-control-handler chain.
///
/// Handlers run last-installed-first; returning `FALSE` from `handler` lets
/// the call fall through to whatever was installed before it. Call
/// [`remove_ctrl_handler`] with the same function pointer to pop it back off
/// — installing the same `fn` item twice pushes two entries.
pub fn install_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: `handler` is a `'static` function pointer of the exact
    // signature `SetConsoleCtrlHandler` requires; `add = TRUE` (1) is a
    // plain flag, not a pointer.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 1) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Pop `handler` off the console-control-handler chain. `handler` must be
/// the same function pointer previously passed to [`install_ctrl_handler`]
/// — Windows matches handlers by pointer identity, not by any handle this
/// module hands back.
pub fn remove_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: see `install_ctrl_handler`; `add = FALSE` (0) removes rather
    // than adds.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 0) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// The current mode flags on `console_handle` — `GetConsoleMode`, the
/// Windows analog of `tcgetattr`.
///
/// # Safety
///
/// `console_handle` must be a currently-open, valid handle to a console
/// input or output buffer.
pub unsafe fn get_mode(console_handle: RawHandle) -> Result<u32, Win32Error> {
    let mut mode: u32 = 0;
    // SAFETY: `console_handle` is caller-supplied per this function's own
    // safety contract; `mode` is a valid out-pointer.
    let ok = unsafe { GetConsoleMode(console_handle, &mut mode) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(mode)
    }
}

/// Set `console_handle`'s mode flags — `SetConsoleMode`, the Windows analog
/// of `tcsetattr`. Which bits to clear/set for a given raw-mode recipe is
/// the caller's decision (see the module-level bit constants above); this
/// function is a plain, policy-free setter.
///
/// # Safety
///
/// `console_handle` must be a currently-open, valid handle to a console
/// input or output buffer.
pub unsafe fn set_mode(console_handle: RawHandle, mode: u32) -> Result<(), Win32Error> {
    // SAFETY: `console_handle` is caller-supplied per this function's own
    // safety contract; `mode` is a plain bitmask, not a pointer.
    let ok = unsafe { SetConsoleMode(console_handle, mode) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Read up to `buf.len()` bytes from `handle` in one call — `ReadFile`, the
/// Windows analog of a raw Unix `read`. With `ENABLE_VIRTUAL_TERMINAL_INPUT`
/// set on an input handle, this delivers a VT/ANSI byte stream a Unix-style
/// key decoder can parse largely unchanged; without it, this reads raw
/// `INPUT_RECORD` bytes, which is almost certainly not what a caller wants
/// (use `ReadConsoleInputW` — out of this crate's current scope — for
/// structured input records instead).
///
/// # Safety
///
/// `handle` must be a currently-open, valid handle open for reading.
pub unsafe fn read(handle: RawHandle, buf: &mut [u8]) -> Result<usize, Win32Error> {
    let mut bytes_read: u32 = 0;
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract; `buf` is a valid, `buf.len()`-byte writable buffer;
    // `bytes_read` is a valid out-pointer; `lpOverlapped = NULL` requests a
    // synchronous (blocking) read, a documented valid input.
    let ok = unsafe {
        ReadFile(
            handle,
            buf.as_mut_ptr(),
            buf.len() as u32,
            &mut bytes_read,
            core::ptr::null_mut(),
        )
    };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(bytes_read as usize)
    }
}

/// Block on `handle` for up to `timeout_ms` — `WaitForSingleObject`, the
/// Windows analog of `poll` on a single fd. Returns `true` if the handle
/// became signaled (input is available, for a console input handle) within
/// the timeout, `false` on timeout.
///
/// # Safety
///
/// `handle` must be a currently-open, valid, waitable handle.
pub unsafe fn wait_readable(handle: RawHandle, timeout_ms: u32) -> Result<bool, Win32Error> {
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract.
    let result = unsafe { WaitForSingleObject(handle, timeout_ms) };
    match result {
        WAIT_OBJECT_0 => Ok(true),
        WAIT_TIMEOUT => Ok(false),
        _ => Err(Win32Error::last()),
    }
}

/// The visible console window size, as `(columns, rows)` —
/// `GetConsoleScreenBufferInfo`, the Windows analog of `TIOCGWINSZ`.
/// Reports the *visible viewport* (`srWindow`), not the full scrollback
/// buffer (`dwSize`, which can be much taller) — the same quantity
/// `ws_col`/`ws_row` report on Unix.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn window_size(console_output: RawHandle) -> Result<(u16, u16), Win32Error> {
    let mut info = ConsoleScreenBufferInfo::default();
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `info` is a valid, correctly-sized out-pointer.
    let ok = unsafe { GetConsoleScreenBufferInfo(console_output, &mut info) };
    if ok == 0 {
        return Err(Win32Error::last());
    }
    let cols = (info.window.right - info.window.left + 1).max(0) as u16;
    let rows = (info.window.bottom - info.window.top + 1).max(0) as u16;
    Ok((cols, rows))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn AllocConsole() -> i32;
        fn GetStdHandle(std_handle: u32) -> RawHandle;
    }
    const STD_INPUT_HANDLE: u32 = -10i32 as u32;
    const STD_OUTPUT_HANDLE: u32 = -11i32 as u32;

    /// A real console input handle, allocating a fresh console if the test
    /// process doesn't already have one — GitHub Actions' `windows-latest`
    /// runner's exact console-attachment state for a `cargo test` process
    /// isn't something this sandbox (no Windows machine) can verify ahead
    /// of time, so this makes the mode/window-size tests below work either
    /// way rather than assuming.
    fn ensure_console_stdin() -> RawHandle {
        // SAFETY: `GetStdHandle` has no precondition.
        let h = unsafe { GetStdHandle(STD_INPUT_HANDLE) };
        // SAFETY: `h` was just obtained from `GetStdHandle`.
        if unsafe { get_mode(h) }.is_ok() {
            return h;
        }
        // SAFETY: `AllocConsole` has no precondition; a failure here (e.g.
        // a console already exists) is handled by re-fetching the std
        // handle regardless, which will then point at whatever console is
        // actually attached.
        unsafe { AllocConsole() };
        // SAFETY: see above.
        unsafe { GetStdHandle(STD_INPUT_HANDLE) }
    }

    extern "system" fn noop_handler(_ctrl_type: u32) -> i32 {
        0
    }

    #[test]
    fn install_then_remove_round_trips() {
        install_ctrl_handler(noop_handler).expect("install should succeed");
        remove_ctrl_handler(noop_handler).expect("remove should succeed");
    }

    #[test]
    fn removing_an_unregistered_handler_fails() {
        extern "system" fn never_installed(_ctrl_type: u32) -> i32 {
            0
        }
        assert!(remove_ctrl_handler(never_installed).is_err());
    }

    #[test]
    fn get_set_mode_round_trip() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid console input handle (obtained
        // or allocated by `ensure_console_stdin`).
        let original = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");

        let toggled = original ^ ENABLE_VIRTUAL_TERMINAL_INPUT;
        // SAFETY: `stdin` is the same valid handle; `toggled` is a plain
        // bitmask derived from a mode Windows itself just reported as
        // valid.
        unsafe { set_mode(stdin, toggled) }.expect("SetConsoleMode should succeed");
        // SAFETY: see above.
        let read_back = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");
        assert_eq!(read_back, toggled);

        // SAFETY: `stdin` is still the same valid handle; restoring the
        // original mode so this test doesn't leak state into others.
        unsafe { set_mode(stdin, original) }.expect("restoring the original mode should succeed");
    }

    #[test]
    fn wait_readable_times_out_with_no_pending_input() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid, waitable console input handle.
        let ready = unsafe { wait_readable(stdin, 0) }.expect("WaitForSingleObject should succeed");
        assert!(
            !ready,
            "no input was queued, so a zero-timeout wait must report not-ready"
        );
    }

    #[test]
    fn window_size_reports_a_plausible_size() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        // SAFETY: `GetStdHandle` has no precondition; fetched only after
        // `ensure_console_stdin` guarantees a console (and thus a paired,
        // valid output buffer) exists.
        let stdout = unsafe { GetStdHandle(STD_OUTPUT_HANDLE) };
        // SAFETY: `stdout` is a valid console output handle per the above.
        let (cols, rows) =
            unsafe { window_size(stdout) }.expect("GetConsoleScreenBufferInfo should succeed");
        assert!(cols > 0, "a real console should report a nonzero width");
        assert!(rows > 0, "a real console should report a nonzero height");
    }
}
