//! `SetConsoleCtrlHandler` — Windows' console-control-event mechanism, the
//! closest analog to `SIGINT`/`SIGTERM`/`SIGHUP` delivery for a console app.
//! Not a signal mask or `sigaction`-alike: handlers run on a dedicated
//! system-created thread, in one process-wide chain (`TRUE`/`FALSE` in
//! `SetConsoleCtrlHandler`'s second argument pushes/pops one entry), and
//! only `CTRL_C_EVENT`/`CTRL_BREAK_EVENT` are events a console app can
//! itself *generate*; `CTRL_CLOSE_EVENT`/`CTRL_LOGOFF_EVENT`/
//! `CTRL_SHUTDOWN_EVENT` are host-delivered shutdown notifications with no
//! Unix signal-number equivalent at all. See rush's
//! `docs/WINDOWS_BACKEND_ANALYSIS.md` §4.4 for the motivating case this
//! module exists for: a `trap 'cmd' TERM` that's silently accepted on
//! Windows today but has nothing installed to ever fire it.

use crate::error::Win32Error;
use crate::handle::RawHandle;

extern crate alloc;

/// Ctrl+C, generated by the console driver (roughly `SIGINT`).
pub const CTRL_C_EVENT: u32 = 0;
/// Ctrl+Break — no Unix keystroke maps to this one.
pub const CTRL_BREAK_EVENT: u32 = 1;
/// The console window is closing (no exact Unix analog; closest in spirit
/// to `SIGHUP`).
pub const CTRL_CLOSE_EVENT: u32 = 2;
/// The current user is logging off (no Unix analog).
pub const CTRL_LOGOFF_EVENT: u32 = 5;
/// The system is shutting down (closest in spirit to `SIGTERM`).
pub const CTRL_SHUTDOWN_EVENT: u32 = 6;

/// A console control handler: called on a dedicated system thread with one
/// of the `CTRL_*_EVENT` constants above. Return nonzero (`TRUE`) to claim
/// the event — stopping it from propagating to the next handler in the
/// chain, or to the default handler, which terminates the process for every
/// event this module defines; return `0` (`FALSE`) to let it fall through.
///
/// `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, and `CTRL_SHUTDOWN_EVENT`
/// handlers get a bounded time budget before Windows kills the process
/// regardless (a few seconds) — keep the handler itself to the same "store
/// an atomic, do nothing else" pattern rush's own `trap::record_signal`
/// already uses for `SIGTERM`/`SIGHUP` on Unix, and let ordinary code pick
/// the stored value up at a safe point afterward.
pub type HandlerRoutine = extern "system" fn(ctrl_type: u32) -> i32;

#[link(name = "kernel32")]
unsafe extern "system" {
    fn SetConsoleCtrlHandler(handler_routine: Option<HandlerRoutine>, add: i32) -> i32;
    fn GenerateConsoleCtrlEvent(ctrl_event: u32, process_group_id: u32) -> i32;
    fn GetConsoleMode(console_handle: RawHandle, mode: *mut u32) -> i32;
    fn SetConsoleMode(console_handle: RawHandle, mode: u32) -> i32;
    fn ReadFile(
        file: RawHandle,
        buffer: *mut u8,
        bytes_to_read: u32,
        bytes_read: *mut u32,
        overlapped: *mut core::ffi::c_void,
    ) -> i32;
    fn GetConsoleScreenBufferInfo(
        console_output: RawHandle,
        buffer_info: *mut ConsoleScreenBufferInfo,
    ) -> i32;
    fn SetConsoleCursorPosition(console_output: RawHandle, cursor_position: Coord) -> i32;
    fn FillConsoleOutputCharacterW(
        console_output: RawHandle,
        character: u16,
        length: u32,
        write_coord: Coord,
        number_of_chars_written: *mut u32,
    ) -> i32;
    fn FillConsoleOutputAttribute(
        console_output: RawHandle,
        attribute: u16,
        length: u32,
        write_coord: Coord,
        number_of_attrs_written: *mut u32,
    ) -> i32;
    fn FlushConsoleInputBuffer(console_input: RawHandle) -> i32;
    fn GetNumberOfConsoleInputEvents(console_input: RawHandle, number_of_events: *mut u32) -> i32;
    fn GetConsoleProcessList(process_list: *mut u32, process_count: u32) -> u32;
    fn GetConsoleWindow() -> *mut core::ffi::c_void;
    fn WaitForSingleObject(handle: RawHandle, milliseconds: u32) -> u32;
    fn WriteConsoleInputW(
        console_input: RawHandle,
        buffer: *const InputRecordKeyEvent,
        length: u32,
        events_written: *mut u32,
    ) -> i32;
    fn GetConsoleCP() -> u32;
    fn SetConsoleCP(code_page_id: u32) -> i32;
    fn GetConsoleOutputCP() -> u32;
    fn SetConsoleOutputCP(code_page_id: u32) -> i32;
    fn GetConsoleTitleW(console_title: *mut u16, size: u32) -> u32;
    fn SetConsoleTitleW(console_title: *const u16) -> i32;
    fn AllocConsole() -> i32;
    fn FreeConsole() -> i32;
    fn AttachConsole(process_id: u32) -> i32;
    fn GetLargestConsoleWindowSize(console_output: RawHandle) -> Coord;
    fn SetConsoleScreenBufferSize(console_output: RawHandle, size: Coord) -> i32;
    fn SetConsoleWindowInfo(
        console_output: RawHandle,
        absolute: i32,
        console_window: *const SmallRect,
    ) -> i32;
}

// `MapVirtualKeyW` lives in user32.dll, not kernel32.dll — this crate's
// first non-kernel32 link (the README's own module docs already flag
// `advapi32.dll` as an expected future addition; user32 is the same kind of
// expansion, needed only for [`write_key_events`]'s scan-code lookup).
#[link(name = "user32")]
unsafe extern "system" {
    fn MapVirtualKeyW(code: u32, map_type: u32) -> u32;
}

/// `MapVirtualKeyW`'s `uMapType`: translate a virtual-key code to the
/// hardware scan code a real keyboard driver would report for it.
const MAPVK_VK_TO_VSC: u32 = 0;

/// The UTF-8 code page identifier, for [`set_input_codepage`]/
/// [`set_output_codepage`] — a console defaults to the system's legacy
/// (OEM/ANSI) code page, which can mis-render non-ASCII bytes even once
/// [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`]/[`ENABLE_VIRTUAL_TERMINAL_INPUT`]
/// are otherwise correctly configured — the Windows analog of making sure a
/// Unix terminal's locale is UTF-8.
pub const CP_UTF8: u32 = 65001;

const WAIT_OBJECT_0: u32 = 0;
const WAIT_TIMEOUT: u32 = 258;

// Console input-mode bits (`GetConsoleMode`/`SetConsoleMode` on an input
// handle). What "raw mode" means in terms of these — which bits to clear
// or set — is deliberately *not* decided here, the same way `rusty_libc`
// exposes `tcgetattr`/`tcsetattr` without baking in a raw-mode recipe:
// that policy belongs to the line-editor consumer (`rusty_lines`'
// `term_sys.rs` on Unix), not this crate.
/// Ctrl+C/Ctrl-Break are intercepted and converted to the corresponding
/// `CTRL_*_EVENT` (via [`install_ctrl_handler`]) rather than delivered as
/// input — set by default. Clearing this is what lets a raw-mode reader see
/// Ctrl+C as ordinary input instead of the OS terminating the process.
pub const ENABLE_PROCESSED_INPUT: u32 = 0x0001;
/// Line-buffered input: `ReadFile`/`ReadConsole` doesn't return until a
/// carriage return, and backspace/editing happens in the console host
/// itself — set by default. The Windows analog of `ICANON`; clear it for
/// the same reason a Unix raw-mode setup clears `ICANON`.
pub const ENABLE_LINE_INPUT: u32 = 0x0002;
/// The console host echoes typed characters — set by default, only
/// meaningful with `ENABLE_LINE_INPUT` also set. The Windows analog of
/// `ECHO`.
pub const ENABLE_ECHO_INPUT: u32 = 0x0004;
/// `WINDOW_BUFFER_SIZE_EVENT` input records are generated on resize.
pub const ENABLE_WINDOW_INPUT: u32 = 0x0008;
/// Mouse events are reported as input records.
pub const ENABLE_MOUSE_INPUT: u32 = 0x0010;
pub const ENABLE_INSERT_MODE: u32 = 0x0020;
/// Mouse/keyboard input is consumed by the console's own Quick Edit
/// selection UI rather than delivered to the application — usually wanted
/// off for a raw-mode reader for the same reason it's wanted off for any
/// full-screen or line-editing console app.
pub const ENABLE_QUICK_EDIT_MODE: u32 = 0x0040;
/// Must be set for `ENABLE_INSERT_MODE`/`ENABLE_QUICK_EDIT_MODE` to have
/// any effect — a documented Windows quirk, not a real feature of its own.
pub const ENABLE_EXTENDED_FLAGS: u32 = 0x0080;
/// `ReadFile`/`ReadConsole` on this input handle delivers a VT/ANSI escape
/// byte stream for special keys (arrows, function keys, …) instead of
/// requiring `ReadConsoleInputW`'s structured `INPUT_RECORD`s — the single
/// bit that makes a Windows 10+ console behave like a Unix tty for input
/// purposes, and the reason this crate's Windows floor (10 1809+) is new
/// enough to support it at all.
pub const ENABLE_VIRTUAL_TERMINAL_INPUT: u32 = 0x0200;

// Console output-mode bits (`GetConsoleMode`/`SetConsoleMode` on an output
// handle).
pub const ENABLE_PROCESSED_OUTPUT: u32 = 0x0001;
pub const ENABLE_WRAP_AT_EOL_OUTPUT: u32 = 0x0002;
/// VT/ANSI escape sequences written to this output handle are interpreted
/// (cursor movement, colors, …) instead of printed literally — the output
/// counterpart of `ENABLE_VIRTUAL_TERMINAL_INPUT`, needed for the same
/// repaint escape sequences a Unix terminal already understands by default.
pub const ENABLE_VIRTUAL_TERMINAL_PROCESSING: u32 = 0x0004;
/// A bare `\n` moves down without returning to column 0 — matching how a
/// Unix terminal's `\n` behaves once `ONLCR`-style translation is off,
/// needed so a VT-aware repaint (which sends its own `\r` where it means
/// it) doesn't get an extra implicit carriage return.
pub const DISABLE_NEWLINE_AUTO_RETURN: u32 = 0x0008;

// CONSOLE_SCREEN_BUFFER_INFO (and its COORD/SMALL_RECT members): `size_of`
// 22, `align_of` 2 on x86_64. Verified against mingw-w64's `wincon.h` the
// same way as `process.rs`/`job.rs`'s structs (a `_Static_assert` probe
// compiled with `x86_64-w64-mingw32-gcc` against the real header).
/// A console character-cell coordinate — `COORD`, e.g. a screen-buffer
/// size or a cursor position. `x` is the column, `y` the row, both
/// 0-based.
#[repr(C)]
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct Coord {
    pub x: i16,
    pub y: i16,
}

/// A console character-cell rectangle — `SMALL_RECT`, e.g. the visible
/// window's extent within the (potentially larger) screen buffer. All
/// four bounds are inclusive, matching `CONSOLE_SCREEN_BUFFER_INFO`'s own
/// `srWindow`.
#[repr(C)]
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct SmallRect {
    pub left: i16,
    pub top: i16,
    pub right: i16,
    pub bottom: i16,
}

#[repr(C)]
#[derive(Default, Clone, Copy)]
struct ConsoleScreenBufferInfo {
    size: Coord,
    cursor_position: Coord,
    attributes: u16,
    window: SmallRect,
    maximum_window_size: Coord,
}
const _: () = assert!(core::mem::size_of::<ConsoleScreenBufferInfo>() == 22);
const _: () = assert!(core::mem::align_of::<ConsoleScreenBufferInfo>() == 2);

/// `KEY_EVENT` — the `EventType` this crate ever writes via
/// [`write_char_events`] (Windows also defines `MOUSE_EVENT`/
/// `WINDOW_BUFFER_SIZE_EVENT`/`MENU_EVENT`/`FOCUS_EVENT`, out of this
/// crate's scope).
const KEY_EVENT: u16 = 0x0001;

// KEY_EVENT_RECORD: `size_of` 16, `align_of` 4 on x86_64. Verified against
// mingw-w64's `wincon.h` the same way as every other struct in this crate
// (a `_Static_assert` probe compiled with `x86_64-w64-mingw32-gcc` against
// the real header). `uChar` is a C union of `WCHAR`/`CHAR`; only the
// (wider) `WCHAR` variant is represented here since this crate only ever
// writes Unicode characters, never `AsciiChar`.
#[repr(C)]
#[derive(Clone, Copy)]
struct KeyEventRecord {
    key_down: i32, // WINBOOL
    repeat_count: u16,
    virtual_key_code: u16,
    virtual_scan_code: u16,
    unicode_char: u16, // uChar union's WCHAR variant
    control_key_state: u32,
}
const _: () = assert!(core::mem::size_of::<KeyEventRecord>() == 16);
const _: () = assert!(core::mem::align_of::<KeyEventRecord>() == 4);

// INPUT_RECORD: `size_of` 20, `align_of` 4 — `EventType` (2 bytes) plus
// `repr(C)`'s automatic 2-byte padding before the (4-byte-aligned) `Event`
// union, which this crate only ever populates as a `KeyEventRecord` (the
// union's widest member, so this struct's total size already matches the
// real `INPUT_RECORD`'s regardless of the other variants this crate never
// constructs).
#[repr(C)]
#[derive(Clone, Copy)]
struct InputRecordKeyEvent {
    event_type: u16,
    key_event: KeyEventRecord,
}
const _: () = assert!(core::mem::size_of::<InputRecordKeyEvent>() == 20);
const _: () = assert!(core::mem::align_of::<InputRecordKeyEvent>() == 4);
const _: () = assert!(core::mem::offset_of!(InputRecordKeyEvent, key_event) == 4);

/// Push `handler` onto the process-wide console-control-handler chain.
///
/// Handlers run last-installed-first; returning `FALSE` from `handler` lets
/// the call fall through to whatever was installed before it. Call
/// [`remove_ctrl_handler`] with the same function pointer to pop it back off
/// — installing the same `fn` item twice pushes two entries.
pub fn install_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: `handler` is a `'static` function pointer of the exact
    // signature `SetConsoleCtrlHandler` requires; `add = TRUE` (1) is a
    // plain flag, not a pointer.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 1) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Pop `handler` off the console-control-handler chain. `handler` must be
/// the same function pointer previously passed to [`install_ctrl_handler`]
/// — Windows matches handlers by pointer identity, not by any handle this
/// module hands back.
pub fn remove_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: see `install_ctrl_handler`; `add = FALSE` (0) removes rather
    // than adds.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 0) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Deliver `ctrl_event` (one of the `CTRL_*_EVENT` constants above) to every
/// process attached to the console that shares `process_group_id` —
/// `GenerateConsoleCtrlEvent`, the counterpart to [`install_ctrl_handler`]
/// on the *sending* side: interrupting a specific child rather than reacting
/// to an interrupt this process received.
///
/// **`process_group_id` only actually scopes [`CTRL_BREAK_EVENT`].** Windows
/// documents `GenerateConsoleCtrlEvent` as failing with
/// `ERROR_INVALID_PARAMETER` for [`CTRL_C_EVENT`] whenever `process_group_id`
/// is nonzero — `CTRL_C_EVENT` can only ever be broadcast to every process
/// sharing the console (`process_group_id == 0`), never targeted at one
/// group. To interrupt just one child process group (e.g. one started with
/// [`crate::process::spawn_suspended`]'s `new_process_group` set), send
/// [`CTRL_BREAK_EVENT`] to its `process_id` instead — this function doesn't
/// pre-validate or silently substitute one event for the other, the same way
/// this crate's other thin wrappers surface the real call's own documented
/// failure rather than inventing a distinct one for the same condition.
pub fn generate_ctrl_event(ctrl_event: u32, process_group_id: u32) -> Result<(), Win32Error> {
    // SAFETY: both arguments are plain values, not pointers.
    let ok = unsafe { GenerateConsoleCtrlEvent(ctrl_event, process_group_id) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// The current mode flags on `console_handle` — `GetConsoleMode`, the
/// Windows analog of `tcgetattr`.
///
/// # Safety
///
/// `console_handle` must be a currently-open, valid handle to a console
/// input or output buffer.
pub unsafe fn get_mode(console_handle: RawHandle) -> Result<u32, Win32Error> {
    let mut mode: u32 = 0;
    // SAFETY: `console_handle` is caller-supplied per this function's own
    // safety contract; `mode` is a valid out-pointer.
    let ok = unsafe { GetConsoleMode(console_handle, &mut mode) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(mode)
    }
}

/// Set `console_handle`'s mode flags — `SetConsoleMode`, the Windows analog
/// of `tcsetattr`. Which bits to clear/set for a given raw-mode recipe is
/// the caller's decision (see the module-level bit constants above); this
/// function is a plain, policy-free setter.
///
/// # Safety
///
/// `console_handle` must be a currently-open, valid handle to a console
/// input or output buffer.
pub unsafe fn set_mode(console_handle: RawHandle, mode: u32) -> Result<(), Win32Error> {
    // SAFETY: `console_handle` is caller-supplied per this function's own
    // safety contract; `mode` is a plain bitmask, not a pointer.
    let ok = unsafe { SetConsoleMode(console_handle, mode) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// The calling process's console input code page — `GetConsoleCP`, the
/// analog of `GetConsoleMode` but for character encoding rather than input
/// behavior. Governs how bytes `ReadFile`/`ReadConsole` deliver (without
/// [`ENABLE_VIRTUAL_TERMINAL_INPUT`]'s VT byte-stream path) are interpreted.
pub fn input_codepage() -> Result<u32, Win32Error> {
    // SAFETY: `GetConsoleCP` takes no arguments and has no precondition
    // beyond "a console may or may not be attached", which it reports as an
    // ordinary `0`/`GetLastError` failure rather than undefined behavior.
    let cp = unsafe { GetConsoleCP() };
    if cp == 0 {
        Err(Win32Error::last())
    } else {
        Ok(cp)
    }
}

/// Set the calling process's console input code page — `SetConsoleCP`. Pass
/// [`CP_UTF8`] so typed non-ASCII characters are interpreted as UTF-8
/// instead of the system's legacy code page.
pub fn set_input_codepage(code_page_id: u32) -> Result<(), Win32Error> {
    // SAFETY: `code_page_id` is a plain value, not a pointer.
    let ok = unsafe { SetConsoleCP(code_page_id) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// The calling process's console output code page — `GetConsoleOutputCP`,
/// the output-side counterpart of [`input_codepage`]. Governs how bytes
/// written to the console (without
/// [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`]'s VT-aware path, which is
/// itself byte-value-agnostic) are decoded for display.
pub fn output_codepage() -> Result<u32, Win32Error> {
    // SAFETY: see `input_codepage` — same "no precondition beyond a
    // possibly-absent console" contract.
    let cp = unsafe { GetConsoleOutputCP() };
    if cp == 0 {
        Err(Win32Error::last())
    } else {
        Ok(cp)
    }
}

/// Set the calling process's console output code page — `SetConsoleOutputCP`.
/// Pass [`CP_UTF8`] so UTF-8 bytes written to the console (e.g. a prompt or
/// completion list containing non-ASCII characters) render correctly instead
/// of being mis-decoded under the system's legacy code page — the single
/// bit that makes a Windows console's *output* behave like a Unix
/// terminal's for non-ASCII text, the same way
/// [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`] does for escape sequences.
pub fn set_output_codepage(code_page_id: u32) -> Result<(), Win32Error> {
    // SAFETY: `code_page_id` is a plain value, not a pointer.
    let ok = unsafe { SetConsoleOutputCP(code_page_id) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// The calling process's console window title — `GetConsoleTitleW`, the
/// Windows analog of xterm's OSC title-setting escape sequence's read-back
/// side. Reports an empty string, not an error, for a console with no title
/// set (`GetConsoleTitleW`'s own documented quirk: a zero return means
/// either "buffer too small" or "empty title," distinguished only by
/// `GetLastError` reporting success in the empty-title case — the same
/// quirk [`crate::process::get_env_var`] handles for
/// `GetEnvironmentVariableW`).
pub fn title() -> Result<alloc::string::String, Win32Error> {
    let mut buf: alloc::vec::Vec<u16> = alloc::vec![0u16; 1024];
    // At most two attempts: an initial try, then one retry sized exactly to
    // whatever `GetConsoleTitleW` reports as actually required (a returned
    // length `>=` the buffer size means it didn't fit) — matching
    // `path::current_dir`'s own growing-buffer pattern.
    for _ in 0..2 {
        // SAFETY: `buf` is a valid, `buf.len()`-element writable buffer.
        let len = unsafe { GetConsoleTitleW(buf.as_mut_ptr(), buf.len() as u32) };
        if len == 0 {
            return match Win32Error::last() {
                Win32Error::SUCCESS => Ok(alloc::string::String::new()),
                err => Err(err),
            };
        }
        if (len as usize) >= buf.len() {
            buf.resize(len as usize + 1, 0);
            continue;
        }
        return Ok(alloc::string::String::from_utf16_lossy(
            &buf[..len as usize],
        ));
    }
    Err(Win32Error::ERROR_INSUFFICIENT_BUFFER)
}

/// Set the calling process's console window title — `SetConsoleTitleW`, the
/// Windows analog of xterm's OSC title-setting escape sequence. A common
/// shell feature (showing the current working directory or running command
/// in the window title) that this crate previously had no primitive for at
/// all.
pub fn set_title(title: &str) -> Result<(), Win32Error> {
    let wide: alloc::vec::Vec<u16> = title.encode_utf16().chain(core::iter::once(0)).collect();
    // SAFETY: `wide` is a valid, NUL-terminated UTF-16 string.
    let ok = unsafe { SetConsoleTitleW(wide.as_ptr()) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Read up to `buf.len()` bytes from `handle` in one call — `ReadFile`, the
/// Windows analog of a raw Unix `read`. With `ENABLE_VIRTUAL_TERMINAL_INPUT`
/// set on an input handle, this delivers a VT/ANSI byte stream a Unix-style
/// key decoder can parse largely unchanged; without it, this reads raw
/// `INPUT_RECORD` bytes, which is almost certainly not what a caller wants
/// (use `ReadConsoleInputW` — out of this crate's current scope — for
/// structured input records instead).
///
/// # Safety
///
/// `handle` must be a currently-open, valid handle open for reading.
pub unsafe fn read(handle: RawHandle, buf: &mut [u8]) -> Result<usize, Win32Error> {
    let mut bytes_read: u32 = 0;
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract; `buf` is a valid, `buf.len()`-byte writable buffer;
    // `bytes_read` is a valid out-pointer; `lpOverlapped = NULL` requests a
    // synchronous (blocking) read, a documented valid input.
    let ok = unsafe {
        ReadFile(
            handle,
            buf.as_mut_ptr(),
            buf.len() as u32,
            &mut bytes_read,
            core::ptr::null_mut(),
        )
    };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(bytes_read as usize)
    }
}

/// Block on `handle` for up to `timeout_ms` — `WaitForSingleObject`, the
/// Windows analog of `poll` on a single fd. Returns `true` if the handle
/// became signaled (input is available, for a console input handle) within
/// the timeout, `false` on timeout.
///
/// # Safety
///
/// `handle` must be a currently-open, valid, waitable handle.
pub unsafe fn wait_readable(handle: RawHandle, timeout_ms: u32) -> Result<bool, Win32Error> {
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract.
    let result = unsafe { WaitForSingleObject(handle, timeout_ms) };
    match result {
        WAIT_OBJECT_0 => Ok(true),
        WAIT_TIMEOUT => Ok(false),
        _ => Err(Win32Error::last()),
    }
}

/// The visible console window size, as `(columns, rows)` —
/// `GetConsoleScreenBufferInfo`, the Windows analog of `TIOCGWINSZ`.
/// Reports the *visible viewport* (`srWindow`), not the full scrollback
/// buffer (`dwSize`, which can be much taller) — the same quantity
/// `ws_col`/`ws_row` report on Unix.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn window_size(console_output: RawHandle) -> Result<(u16, u16), Win32Error> {
    let mut info = ConsoleScreenBufferInfo::default();
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `info` is a valid, correctly-sized out-pointer.
    let ok = unsafe { GetConsoleScreenBufferInfo(console_output, &mut info) };
    if ok == 0 {
        return Err(Win32Error::last());
    }
    let cols = (info.window.right - info.window.left + 1).max(0) as u16;
    let rows = (info.window.bottom - info.window.top + 1).max(0) as u16;
    Ok((cols, rows))
}

/// The largest the console window could be resized to, in character
/// cells, given the current font and the display it's on —
/// `GetLargestConsoleWindowSize`. The write-side counterpart to
/// [`window_size`]'s read-only report: a caller planning a
/// [`set_screen_buffer_size`]/[`set_window_info`] resize needs this as the
/// upper bound, since requesting a window larger than this fails.
/// Documented as reporting `(0, 0)` on failure rather than a separate
/// error path — matching this crate's already-established "never fails in
/// practice" pattern (e.g. `GetDriveTypeW`) since a real console can't
/// legitimately have a zero-cell maximum.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn largest_window_size(console_output: RawHandle) -> Coord {
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `GetLargestConsoleWindowSize` has no other
    // precondition and returns a plain-data `COORD` by value.
    unsafe { GetLargestConsoleWindowSize(console_output) }
}

/// Resize the screen buffer (the full scrollback extent, `dwSize` in
/// `CONSOLE_SCREEN_BUFFER_INFO` — not the visible window; see
/// [`set_window_info`] for that) — `SetConsoleScreenBufferSize`. Fails
/// with `ERROR_INVALID_PARAMETER` if `size` is smaller than the current
/// visible window in either dimension, since the buffer can never be
/// smaller than what's currently shown.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn set_screen_buffer_size(
    console_output: RawHandle,
    size: Coord,
) -> Result<(), Win32Error> {
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `size` is a plain-data struct passed by value, not
    // a pointer.
    let ok = unsafe { SetConsoleScreenBufferSize(console_output, size) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Resize/reposition the visible window within the screen buffer (the
/// `srWindow` half of console geometry — not the buffer itself; see
/// [`set_screen_buffer_size`] for that) — `SetConsoleWindowInfo`.
/// `absolute` selects whether `rect` is the window's new absolute bounds
/// (`true`) or an offset added to its current bounds (`false`, matching
/// `SetConsoleWindowInfo`'s own `bAbsolute` parameter). Fails with
/// `ERROR_INVALID_PARAMETER` if `rect` would place the window outside the
/// current screen buffer or past [`largest_window_size`].
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn set_window_info(
    console_output: RawHandle,
    absolute: bool,
    rect: SmallRect,
) -> Result<(), Win32Error> {
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `&rect` is a valid pointer to a plain-data struct
    // live for the whole call.
    let ok = unsafe { SetConsoleWindowInfo(console_output, i32::from(absolute), &rect) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Move the cursor to `(x, y)` (0-based column/row, relative to the screen
/// buffer's origin, same coordinate space `window_size`'s underlying
/// `CONSOLE_SCREEN_BUFFER_INFO.dwCursorPosition` reports) —
/// `SetConsoleCursorPosition`. Needed by a raw-mode line editor
/// (`rusty_lines`) doing multi-line prompt redraws that must reposition the
/// cursor directly rather than relying on a VT-escape-sequence fallback,
/// which this crate assumes no caller has anywhere else.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn set_cursor_position(
    console_output: RawHandle,
    x: i16,
    y: i16,
) -> Result<(), Win32Error> {
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `Coord { x, y }` is a plain-data struct passed by
    // value, not a pointer.
    let ok = unsafe { SetConsoleCursorPosition(console_output, Coord { x, y }) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Write `ch` `count` times starting at `(x, y)`, without moving the
/// cursor — `FillConsoleOutputCharacterW`. The character-content half of a
/// clear-to-end-of-line redraw (pair with [`fill_attribute`] to also reset
/// color/attributes over the same span): a shorter re-rendered prompt line
/// needs this to erase whatever longer content it's replacing, the same
/// role a VT `\x1b[K` escape plays for a caller that assumes that path
/// instead — this crate doesn't assume every consumer does. Returns the
/// number of characters actually written, which is less than `count` if
/// `(x, y) + count` runs past the end of the screen buffer.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn fill_char(
    console_output: RawHandle,
    ch: u16,
    x: i16,
    y: i16,
    count: u32,
) -> Result<u32, Win32Error> {
    let mut written: u32 = 0;
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `Coord { x, y }` is a plain-data struct passed by
    // value, not a pointer; `written` is a valid out-pointer.
    let ok = unsafe {
        FillConsoleOutputCharacterW(console_output, ch, count, Coord { x, y }, &mut written)
    };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(written)
    }
}

/// Set the character attribute (color/style bits) `count` times starting at
/// `(x, y)`, without changing the underlying character content or moving
/// the cursor — `FillConsoleOutputAttribute`, the attribute-content
/// counterpart to [`fill_char`]. Returns the number of cells actually
/// written, which is less than `count` if `(x, y) + count` runs past the
/// end of the screen buffer.
///
/// # Safety
///
/// `console_output` must be a currently-open, valid handle to a console
/// output buffer.
pub unsafe fn fill_attribute(
    console_output: RawHandle,
    attribute: u16,
    x: i16,
    y: i16,
    count: u32,
) -> Result<u32, Win32Error> {
    let mut written: u32 = 0;
    // SAFETY: `console_output` is caller-supplied per this function's own
    // safety contract; `Coord { x, y }` is a plain-data struct passed by
    // value, not a pointer; `written` is a valid out-pointer.
    let ok = unsafe {
        FillConsoleOutputAttribute(
            console_output,
            attribute,
            count,
            Coord { x, y },
            &mut written,
        )
    };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(written)
    }
}

/// Discard every currently-queued, not-yet-read input event on
/// `console_input` — `FlushConsoleInputBuffer`. Needed for dropping stale
/// keystrokes buffered during a slow command so they don't replay into the
/// next prompt, most noticeable right after `Ctrl-C` interrupts something
/// while a user kept typing.
///
/// # Safety
///
/// `console_input` must be a currently-open, valid console input handle.
pub unsafe fn flush_input(console_input: RawHandle) -> Result<(), Win32Error> {
    // SAFETY: `console_input` is caller-supplied per this function's own
    // safety contract.
    let ok = unsafe { FlushConsoleInputBuffer(console_input) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// How many input events are currently queued on `console_input`, without
/// consuming any of them — `GetNumberOfConsoleInputEvents`, the console-input
/// analog of [`crate::handle::pipe_bytes_available`]'s non-blocking "how
/// much is ready" check for pipes. Unlike [`wait_readable`], which can only
/// answer "is at least one event ready" (and, for a nonzero timeout,
/// blocks), this is an instantaneous depth check.
///
/// # Safety
///
/// `console_input` must be a currently-open, valid console input handle.
pub unsafe fn pending_input_events(console_input: RawHandle) -> Result<u32, Win32Error> {
    let mut count: u32 = 0;
    // SAFETY: `console_input` is caller-supplied per this function's own
    // safety contract; `count` is a valid out-pointer.
    let ok = unsafe { GetNumberOfConsoleInputEvents(console_input, &mut count) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(count)
    }
}

/// The pids of every process currently attached to the calling process's
/// console — `GetConsoleProcessList`, e.g. for an "is anything else still
/// attached to this console" check. No current `rush` feature asks for
/// this; filed for Win32 parity.
pub fn process_list() -> Result<alloc::vec::Vec<u32>, Win32Error> {
    let mut buf: alloc::vec::Vec<u32> = alloc::vec![0u32; 8];
    // `GetConsoleProcessList` reports how many pids it actually needed
    // (which can be larger than the buffer just tried) in its own return
    // value — grow to that exact size and retry, the same shape this
    // crate's other "ask, then maybe grow" calls use, just via a return
    // value instead of an `ERROR_INSUFFICIENT_BUFFER`/ in-out size
    // parameter.
    for _ in 0..2 {
        // SAFETY: `buf` is a valid, `buf.len()`-element writable buffer
        // matched by the `process_count` argument naming its exact
        // length.
        let needed = unsafe { GetConsoleProcessList(buf.as_mut_ptr(), buf.len() as u32) };
        if needed == 0 {
            return Err(Win32Error::last());
        }
        if (needed as usize) > buf.len() {
            buf.resize(needed as usize, 0);
            continue;
        }
        buf.truncate(needed as usize);
        return Ok(buf);
    }
    Err(Win32Error::ERROR_INSUFFICIENT_BUFFER)
}

/// The `HWND` of the console window attached to the calling process, if
/// any — `GetConsoleWindow`. `None` for a process with no console window
/// (e.g. a headless/service process). Manipulating the window itself
/// (position/focus/etc.) via ordinary `user32` window APIs is out of this
/// crate's scope beyond returning the handle. No `Result`: `GetConsoleWindow`
/// has no documented failure mode beyond the `None` case itself, matching
/// this crate's already-established "never fails" pattern (e.g.
/// `GetDriveTypeW`). No current `rush` feature asks for this; filed for
/// Win32 parity.
pub fn window_handle() -> Option<*mut core::ffi::c_void> {
    // SAFETY: `GetConsoleWindow` takes no arguments and has no
    // precondition.
    let hwnd = unsafe { GetConsoleWindow() };
    if hwnd.is_null() { None } else { Some(hwnd) }
}

/// `AttachConsole`'s `dwProcessId` sentinel: attach to the console of the
/// calling process's own parent, rather than a specific pid.
pub const ATTACH_PARENT_PROCESS: u32 = 0xFFFF_FFFF;

/// Allocate a brand-new console for the calling process — `AllocConsole`.
/// Fails with `ERROR_ACCESS_DENIED` if the process already has a console.
/// Needed by a GUI-subsystem process that wants to acquire a console on
/// demand; this crate's own tests already use `AllocConsole` internally
/// (see `ensure_console_stdin` below) but hadn't exposed it as public API
/// until now. No current `rush` feature asks for this; filed for Win32
/// parity.
pub fn alloc() -> Result<(), Win32Error> {
    // SAFETY: `AllocConsole` takes no arguments and has no precondition.
    if unsafe { AllocConsole() } == 0 {
        return Err(Win32Error::last());
    }
    Ok(())
}

/// Detach the calling process from its console — `FreeConsole`. A
/// GUI-subsystem process that acquired a console via [`alloc`] (or
/// inherited one) can use this to give it up again, e.g. before calling
/// [`alloc`] a second time to create a fresh one.
pub fn free() -> Result<(), Win32Error> {
    // SAFETY: `FreeConsole` takes no arguments and has no precondition.
    if unsafe { FreeConsole() } == 0 {
        return Err(Win32Error::last());
    }
    Ok(())
}

/// Attach the calling process to the console of another process —
/// `AttachConsole`. `pid = None` maps to `ATTACH_PARENT_PROCESS`, attaching
/// to whatever console (if any) launched this process — the usual case
/// for a GUI-subsystem process that wants to reuse a console its parent
/// already has, rather than allocate its own via [`alloc`]. The calling
/// process must not already have a console (see [`free`]).
pub fn attach(pid: Option<u32>) -> Result<(), Win32Error> {
    let process_id = pid.unwrap_or(ATTACH_PARENT_PROCESS);
    // SAFETY: `AttachConsole` takes a plain `DWORD` process id (or the
    // documented `ATTACH_PARENT_PROCESS` sentinel) and has no other
    // precondition.
    if unsafe { AttachConsole(process_id) } == 0 {
        return Err(Win32Error::last());
    }
    Ok(())
}

/// Synthesize `text` as a sequence of real console key events —
/// `WriteConsoleInputW`, the standard, documented technique console
/// automation tools use to inject keystrokes (queues `INPUT_RECORD`s into
/// the same input buffer a real keyboard driver would). Each character
/// becomes a key-down/key-up pair carrying it via `uChar`, not a real
/// virtual-key code — valid for ordinary printable characters *and* ASCII
/// control characters (`'\r'`, `\x03` for Ctrl-C, `\x10` for Ctrl-P, …:
/// Windows' own real key events for those carry exactly these `uChar`
/// values), but not for non-character keys (arrows, function keys, Home/
/// End) that carry no `uChar` at all — those need real virtual-key codes,
/// out of this function's scope. Returns the number of events written
/// (twice the character count, barring a partial write).
///
/// With `ENABLE_VIRTUAL_TERMINAL_INPUT` set on `handle` (see
/// [`ENABLE_VIRTUAL_TERMINAL_INPUT`]), a subsequent [`read`] on the same
/// handle observes these as the equivalent VT/ANSI byte(s) — the same
/// translation a real keypress goes through — making this the primitive a
/// test can use to drive a raw-mode reader through its real Windows I/O
/// path end to end, the Windows analog of writing bytes into one end of a
/// Unix pty.
///
/// # Safety
///
/// `handle` must be a currently-open, valid console input handle.
pub unsafe fn write_char_events(handle: RawHandle, text: &str) -> Result<u32, Win32Error> {
    extern crate alloc;
    use alloc::vec::Vec;

    let mut records: Vec<InputRecordKeyEvent> = Vec::with_capacity(text.chars().count() * 2);
    for ch in text.chars() {
        let mut units = [0u16; 2];
        for &unit in ch.encode_utf16(&mut units).iter() {
            for key_down in [1i32, 0i32] {
                records.push(InputRecordKeyEvent {
                    event_type: KEY_EVENT,
                    key_event: KeyEventRecord {
                        key_down,
                        repeat_count: 1,
                        virtual_key_code: 0,
                        virtual_scan_code: 0,
                        unicode_char: unit,
                        control_key_state: 0,
                    },
                });
            }
        }
    }
    let mut written: u32 = 0;
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract; `records` is a valid buffer of exactly `records.len()`
    // initialized `InputRecordKeyEvent`s; `written` is a valid out-pointer.
    let ok =
        unsafe { WriteConsoleInputW(handle, records.as_ptr(), records.len() as u32, &mut written) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(written)
    }
}

// Non-character virtual-key codes for [`write_key_events`] — arrows,
// Home/End, and friends carry no `uChar` at all, so [`write_char_events`]
// can't synthesize them; these are the ones a line editor's cursor/history
// navigation or keymap most plausibly needs to test.
pub const VK_PRIOR: u16 = 0x21;
pub const VK_NEXT: u16 = 0x22;
pub const VK_END: u16 = 0x23;
pub const VK_HOME: u16 = 0x24;
pub const VK_LEFT: u16 = 0x25;
pub const VK_UP: u16 = 0x26;
pub const VK_RIGHT: u16 = 0x27;
pub const VK_DOWN: u16 = 0x28;
pub const VK_INSERT: u16 = 0x2D;
pub const VK_DELETE: u16 = 0x2E;
pub const VK_F1: u16 = 0x70;
pub const VK_F2: u16 = 0x71;
pub const VK_F3: u16 = 0x72;
pub const VK_F4: u16 = 0x73;
pub const VK_F5: u16 = 0x74;
pub const VK_F6: u16 = 0x75;
pub const VK_F7: u16 = 0x76;
pub const VK_F8: u16 = 0x77;
pub const VK_F9: u16 = 0x78;
pub const VK_F10: u16 = 0x79;
pub const VK_F11: u16 = 0x7A;
pub const VK_F12: u16 = 0x7B;

/// `KEY_EVENT_RECORD.dwControlKeyState` bit a real keyboard driver always
/// sets for the navigation-cluster keys ([`VK_PRIOR`]/[`VK_NEXT`]/
/// [`VK_END`]/[`VK_HOME`]/[`VK_LEFT`]/[`VK_UP`]/[`VK_RIGHT`]/[`VK_DOWN`]/
/// [`VK_INSERT`]/[`VK_DELETE`]) — distinguishes them from their
/// numeric-keypad counterparts. [`write_key_events`] sets this
/// automatically for those keys rather than leaving a caller to remember
/// it, the one place this module deviates from its usual "thin,
/// policy-free wrapper" rule, since a real driver never *not* sets it for
/// these keys — there's no real policy choice here to leave to the caller.
pub const ENHANCED_KEY: u32 = 0x0100;

/// Synthesize one non-character key (arrows, Home/End, function keys, …) —
/// `WriteConsoleInputW`, the virtual-key-code counterpart to
/// [`write_char_events`]. `control_key_state` carries modifier bits (Shift/
/// Ctrl/Alt — not named as constants here, since Windows' own
/// `KEY_EVENT_RECORD.dwControlKeyState` values are already documented
/// bit-for-bit and this is a thin passthrough); pass `0` for an unmodified
/// keypress. [`ENHANCED_KEY`] is OR'd in automatically for the
/// navigation-cluster keys listed on its own doc — a caller doesn't need to
/// set it themselves.
///
/// The hardware scan code Windows pairs with `virtual_key_code` is looked
/// up via `MapVirtualKeyW` rather than left as `0` — the same "queue what a
/// real keyboard driver would" fidelity [`write_char_events`]'s own doc
/// describes, just extended to the one field that primitive never needed
/// (a character key's scan code is immaterial to VT translation the way a
/// non-character key's is).
///
/// # Safety
///
/// `handle` must be a currently-open, valid console input handle.
pub unsafe fn write_key_events(
    handle: RawHandle,
    virtual_key_code: u16,
    control_key_state: u32,
) -> Result<u32, Win32Error> {
    let is_enhanced = matches!(
        virtual_key_code,
        VK_PRIOR
            | VK_NEXT
            | VK_END
            | VK_HOME
            | VK_LEFT
            | VK_UP
            | VK_RIGHT
            | VK_DOWN
            | VK_INSERT
            | VK_DELETE
    );
    let control_key_state = control_key_state | if is_enhanced { ENHANCED_KEY } else { 0 };

    // SAFETY: `MAPVK_VK_TO_VSC` is the documented map-type constant for
    // this direction; `virtual_key_code` is a plain value, not a pointer.
    let scan_code = unsafe { MapVirtualKeyW(u32::from(virtual_key_code), MAPVK_VK_TO_VSC) } as u16;

    let records = [1i32, 0i32].map(|key_down| InputRecordKeyEvent {
        event_type: KEY_EVENT,
        key_event: KeyEventRecord {
            key_down,
            repeat_count: 1,
            virtual_key_code,
            virtual_scan_code: scan_code,
            unicode_char: 0,
            control_key_state,
        },
    });

    let mut written: u32 = 0;
    // SAFETY: `handle` is caller-supplied per this function's own safety
    // contract; `records` is a valid, fully-initialized 2-element buffer;
    // `written` is a valid out-pointer.
    let ok =
        unsafe { WriteConsoleInputW(handle, records.as_ptr(), records.len() as u32, &mut written) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(written)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    extern crate alloc;

    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn CreateFileW(
            file_name: *const u16,
            desired_access: u32,
            share_mode: u32,
            security_attributes: *const core::ffi::c_void,
            creation_disposition: u32,
            flags_and_attributes: u32,
            template_file: RawHandle,
        ) -> RawHandle;
    }
    const GENERIC_READ: u32 = 0x8000_0000;
    const GENERIC_WRITE: u32 = 0x4000_0000;
    const FILE_SHARE_READ: u32 = 0x0000_0001;
    const FILE_SHARE_WRITE: u32 = 0x0000_0002;
    const OPEN_EXISTING: u32 = 3;

    /// Open a real handle to whatever console this process is attached to
    /// — `CreateFileW("CONIN$"/"CONOUT$", …)`, Microsoft's own documented
    /// way to get a console handle. Deliberately **not** `GetStdHandle`:
    /// if the test process's std handles were redirected (e.g. `cargo
    /// test` under a CI runner with stdin closed/NUL), `GetStdHandle`
    /// keeps returning the redirected handle even after `AllocConsole`
    /// gives the process a real console — a documented Windows quirk
    /// found the hard way (the first version of this test used
    /// `GetStdHandle` and failed on `windows-latest` CI with
    /// `ERROR_INVALID_HANDLE`). `CONIN$`/`CONOUT$` sidestep the whole
    /// redirection question by always naming the *actual* attached
    /// console, whatever the std handles say.
    fn open_console(name: &str) -> Option<RawHandle> {
        let wide: alloc::vec::Vec<u16> = name.encode_utf16().chain(core::iter::once(0)).collect();
        // SAFETY: `wide` is a valid, NUL-terminated UTF-16 string naming a
        // well-known console pseudo-device; the other arguments are
        // documented-valid constants for opening an existing device for
        // read/write, shared.
        let h = unsafe {
            CreateFileW(
                wide.as_ptr(),
                GENERIC_READ | GENERIC_WRITE,
                FILE_SHARE_READ | FILE_SHARE_WRITE,
                core::ptr::null(),
                OPEN_EXISTING,
                0,
                core::ptr::null_mut(),
            )
        };
        if h.is_null() || h as isize == -1 {
            None
        } else {
            Some(h)
        }
    }

    /// A real console input handle, allocating a fresh console via
    /// `AllocConsole` if the test process doesn't already have one
    /// attached — GitHub Actions' `windows-latest` runner's exact
    /// console-attachment state for a `cargo test` process isn't something
    /// this sandbox (no Windows machine) can verify ahead of time, so this
    /// makes the mode/window-size tests below work either way rather than
    /// assuming.
    fn ensure_console_stdin() -> RawHandle {
        if let Some(h) = open_console("CONIN$") {
            return h;
        }
        // A failure here (e.g. a console already exists under a name this
        // function didn't manage to open for an unrelated reason) is
        // handled by the `expect` below surfacing a clear panic rather
        // than silently returning a null/invalid handle.
        let _ = alloc();
        open_console("CONIN$").expect("AllocConsole should provide an openable console")
    }

    extern "system" fn noop_handler(_ctrl_type: u32) -> i32 {
        0
    }

    #[test]
    fn install_then_remove_round_trips() {
        install_ctrl_handler(noop_handler).expect("install should succeed");
        remove_ctrl_handler(noop_handler).expect("remove should succeed");
    }

    #[test]
    fn removing_an_unregistered_handler_fails() {
        extern "system" fn never_installed(_ctrl_type: u32) -> i32 {
            0
        }
        assert!(remove_ctrl_handler(never_installed).is_err());
    }

    #[test]
    fn ctrl_c_event_cannot_be_scoped_to_a_process_group() {
        // The documented Win32 constraint this module's own doc comment
        // calls out: `CTRL_C_EVENT` can only ever be broadcast console-wide
        // (`process_group_id == 0`) — passing any nonzero group id fails
        // with `ERROR_INVALID_PARAMETER`, the same way `wait_any` surfaces
        // `WaitForMultipleObjects`'s own documented limit rather than this
        // crate pre-validating and inventing a distinct error. A made-up,
        // certainly-nonexistent group id is used here since the failure is
        // about the *event type*/*nonzero-ness* combination, not about
        // whether the id names a real group.
        let err = generate_ctrl_event(CTRL_C_EVENT, 0xFFFF).unwrap_err();
        assert_eq!(err, Win32Error::ERROR_INVALID_PARAMETER);
    }

    #[test]
    fn get_set_mode_round_trip() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid console input handle (obtained
        // or allocated by `ensure_console_stdin`).
        let original = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");

        let toggled = original ^ ENABLE_VIRTUAL_TERMINAL_INPUT;
        // SAFETY: `stdin` is the same valid handle; `toggled` is a plain
        // bitmask derived from a mode Windows itself just reported as
        // valid.
        unsafe { set_mode(stdin, toggled) }.expect("SetConsoleMode should succeed");
        // SAFETY: see above.
        let read_back = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");
        assert_eq!(read_back, toggled);

        // SAFETY: `stdin` is still the same valid handle; restoring the
        // original mode so this test doesn't leak state into others.
        unsafe { set_mode(stdin, original) }.expect("restoring the original mode should succeed");
    }

    #[test]
    fn input_codepage_round_trips_through_utf8() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let original = input_codepage().expect("GetConsoleCP should succeed");

        set_input_codepage(CP_UTF8).expect("SetConsoleCP should succeed");
        assert_eq!(input_codepage().unwrap(), CP_UTF8);

        // Restore the original code page so this test doesn't leak state
        // into others.
        set_input_codepage(original).expect("restoring the original code page should succeed");
    }

    #[test]
    fn output_codepage_round_trips_through_utf8() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let original = output_codepage().expect("GetConsoleOutputCP should succeed");

        set_output_codepage(CP_UTF8).expect("SetConsoleOutputCP should succeed");
        assert_eq!(output_codepage().unwrap(), CP_UTF8);

        // Restore the original code page so this test doesn't leak state
        // into others.
        set_output_codepage(original).expect("restoring the original code page should succeed");
    }

    #[test]
    fn set_title_then_title_round_trips() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let original = title().expect("GetConsoleTitleW should succeed");

        set_title("rusty_win32 test title").expect("SetConsoleTitleW should succeed");
        assert_eq!(title().unwrap(), "rusty_win32 test title");

        // Restore the original title so this test doesn't leak state into
        // others.
        set_title(&original).expect("restoring the original title should succeed");
    }

    #[test]
    fn wait_readable_times_out_with_no_pending_input() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid, waitable console input handle.
        let ready = unsafe { wait_readable(stdin, 0) }.expect("WaitForSingleObject should succeed");
        assert!(
            !ready,
            "no input was queued, so a zero-timeout wait must report not-ready"
        );
    }

    #[test]
    fn flush_input_discards_queued_keystrokes() {
        let stdin = ensure_console_stdin();

        // SAFETY: `stdin` is a real, valid console input handle.
        unsafe { write_char_events(stdin, "a") }.expect("WriteConsoleInputW should succeed");
        // SAFETY: same handle.
        let ready_before =
            unsafe { wait_readable(stdin, 0) }.expect("WaitForSingleObject should succeed");
        assert!(ready_before, "queued input should make the handle ready");

        // SAFETY: `stdin` is a valid console input handle; this is the
        // operation under test.
        unsafe { flush_input(stdin) }.expect("FlushConsoleInputBuffer should succeed");

        // SAFETY: same handle.
        let ready_after =
            unsafe { wait_readable(stdin, 0) }.expect("WaitForSingleObject should succeed");
        assert!(
            !ready_after,
            "flushing should discard the queued keystrokes"
        );
    }

    #[test]
    fn pending_input_events_reports_the_queued_count() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid console input handle; this
        // clears out anything a prior test in the same process left queued.
        unsafe { flush_input(stdin) }.expect("FlushConsoleInputBuffer should succeed");

        // SAFETY: same handle.
        let before = unsafe { pending_input_events(stdin) }
            .expect("GetNumberOfConsoleInputEvents should succeed");
        assert_eq!(before, 0, "a freshly flushed input buffer should be empty");

        // SAFETY: same handle.
        let written =
            unsafe { write_char_events(stdin, "a") }.expect("WriteConsoleInputW should succeed");

        // SAFETY: same handle.
        let after = unsafe { pending_input_events(stdin) }
            .expect("GetNumberOfConsoleInputEvents should succeed");
        assert_eq!(
            after, written,
            "queued count should match what was just written"
        );

        // SAFETY: same handle; leave the input buffer clean for other tests.
        unsafe { flush_input(stdin) }.expect("FlushConsoleInputBuffer should succeed");
    }

    #[test]
    fn process_list_includes_the_calling_process_itself() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let pids = process_list().expect("GetConsoleProcessList should succeed");
        assert!(
            pids.contains(&crate::process::current_pid()),
            "the calling process should be attached to its own console, got: {pids:?}"
        );
    }

    #[test]
    fn window_handle_is_stable_across_repeated_calls() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        // `GetConsoleWindow` can validly return `NULL` even once a console
        // exists — not every hosting scenario (e.g. a non-interactive CI
        // runner's session) attaches a real window to it, confirmed by
        // this exact assumption failing on this crate's own
        // `windows-latest` CI runner. So this only checks that repeated
        // calls agree with each other, not that the handle is non-null.
        let first = window_handle();
        let second = window_handle();
        assert_eq!(
            first, second,
            "GetConsoleWindow should report the same answer on repeated calls"
        );
    }

    #[test]
    fn alloc_fails_when_a_console_is_already_attached() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let err = alloc().expect_err("AllocConsole should fail: a console is already attached");
        assert_eq!(err, Win32Error::ERROR_ACCESS_DENIED);
    }

    #[test]
    fn free_then_alloc_round_trips_to_a_working_console() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        free().expect("FreeConsole should succeed while a console is attached");
        alloc().expect("AllocConsole should succeed once no console is attached");
        assert!(
            open_console("CONIN$").is_some(),
            "a fresh console from alloc() should be openable"
        );
    }

    #[test]
    fn attach_fails_when_a_console_is_already_attached() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        // Deliberately never call `free()` here: unlike
        // `free_then_alloc_round_trips_to_a_working_console`, this test
        // doesn't need to detach at all — `AttachConsole` is documented to
        // reject the call outright whenever the calling process already
        // has a console, before it even looks at the target pid. That
        // makes this exercise `attach`'s error path without ever leaving
        // the shared test-process console detached, which a prior version
        // of this test did (attaching to a spawned child's inherited
        // console) — CI proved that reattachment doesn't reliably succeed
        // in this hosting environment, and a failed `attach()` after an
        // unconditional `free()` left the process console-less for every
        // test that ran after it alphabetically.
        let err = attach(None).expect_err("AttachConsole should fail: already have a console");
        assert_eq!(err, Win32Error::ERROR_ACCESS_DENIED);
    }

    #[test]
    fn window_size_reports_a_plausible_size() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");
        // SAFETY: `stdout` is a valid console output handle per the above.
        let (cols, rows) =
            unsafe { window_size(stdout) }.expect("GetConsoleScreenBufferInfo should succeed");
        assert!(cols > 0, "a real console should report a nonzero width");
        assert!(rows > 0, "a real console should report a nonzero height");
    }

    #[test]
    fn largest_window_size_reports_a_plausible_maximum() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");
        // SAFETY: `stdout` is a valid console output handle per the above.
        let size = unsafe { largest_window_size(stdout) };
        assert!(
            size.x > 0 && size.y > 0,
            "a real console should report a nonzero maximum window size, got {size:?}"
        );
    }

    #[test]
    fn set_screen_buffer_size_then_read_back_round_trips() {
        let stdin = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");

        let mut info = ConsoleScreenBufferInfo::default();
        // SAFETY: `stdout` is a valid console output handle; `info` is a
        // valid, correctly-sized out-pointer.
        let ok = unsafe { GetConsoleScreenBufferInfo(stdout, &mut info) };
        assert_ne!(ok, 0, "GetConsoleScreenBufferInfo should succeed");
        let original = info.size;

        // Only ever grows the buffer (never shrinks below the current
        // visible window), so this can't fail with
        // `ERROR_INVALID_PARAMETER` regardless of the window's own
        // current extent.
        let grown = Coord {
            x: original.x,
            y: original.y + 1,
        };
        // SAFETY: `stdout` is the same valid handle; this is the
        // operation under test.
        unsafe { set_screen_buffer_size(stdout, grown) }
            .expect("SetConsoleScreenBufferSize should succeed growing the buffer");

        let mut after = ConsoleScreenBufferInfo::default();
        // SAFETY: see above.
        let ok = unsafe { GetConsoleScreenBufferInfo(stdout, &mut after) };
        assert_ne!(ok, 0, "GetConsoleScreenBufferInfo should succeed");
        assert_eq!(after.size, grown);

        // Restore the original size so this test doesn't leak state into
        // others.
        // SAFETY: `stdout` is still the same valid handle; `original` was
        // already a valid size for this same buffer/window before this
        // test ran.
        unsafe { set_screen_buffer_size(stdout, original) }
            .expect("restoring the original screen buffer size should succeed");

        // A screen-buffer resize queues a real `WINDOW_BUFFER_SIZE_EVENT`
        // into the console's shared input buffer (confirmed by this exact
        // test breaking `wait_readable_times_out_with_no_pending_input`,
        // which runs later alphabetically, in this crate's own CI) — flush
        // it so this test doesn't leave input state for a later test to
        // inherit, the same discipline `console::attach`'s test fix
        // established for the console handle itself.
        // SAFETY: `stdin` is a valid console input handle per
        // `ensure_console_stdin`'s own contract.
        unsafe { flush_input(stdin) }.expect("FlushConsoleInputBuffer should succeed");
    }

    #[test]
    fn set_window_info_accepts_a_zero_relative_move() {
        let stdin = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");
        // A zero-delta relative move changes nothing about the window's
        // actual bounds, so it can't fail or leave any *geometry* state
        // for a later test to inherit — unlike a real resize/reposition,
        // which would risk exactly the kind of shared-state leakage the
        // `console::attach` test caused earlier in this crate's history.
        // SAFETY: `stdout` is a valid console output handle per the
        // above; this is the operation under test.
        unsafe { set_window_info(stdout, false, SmallRect::default()) }
            .expect("SetConsoleWindowInfo should accept a zero-delta relative move");

        // Even a zero-delta window-info call may still queue a
        // `WINDOW_BUFFER_SIZE_EVENT` (the API has no way to know the
        // caller considers this a no-op) — flush defensively, matching
        // `set_screen_buffer_size_then_read_back_round_trips`'s fix for
        // the same real behavior.
        // SAFETY: `stdin` is a valid console input handle per
        // `ensure_console_stdin`'s own contract.
        unsafe { flush_input(stdin) }.expect("FlushConsoleInputBuffer should succeed");
    }

    #[test]
    fn set_cursor_position_moves_the_cursor() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");

        // SAFETY: `stdout` is a valid console output handle per the above;
        // this is the operation under test.
        unsafe { set_cursor_position(stdout, 3, 2) }
            .expect("SetConsoleCursorPosition should succeed");

        let mut info = ConsoleScreenBufferInfo::default();
        // SAFETY: `stdout` is a valid console output handle; `info` is a
        // valid, correctly-sized out-pointer.
        let ok = unsafe { GetConsoleScreenBufferInfo(stdout, &mut info) };
        assert_ne!(ok, 0, "GetConsoleScreenBufferInfo should succeed");
        assert_eq!(info.cursor_position.x, 3);
        assert_eq!(info.cursor_position.y, 2);
    }

    #[test]
    fn fill_char_writes_the_requested_count() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");

        // SAFETY: `stdout` is a valid console output handle per the above.
        let written = unsafe { fill_char(stdout, u16::from(b'x'), 0, 0, 5) }
            .expect("FillConsoleOutputCharacterW should succeed");
        assert_eq!(written, 5);
    }

    #[test]
    fn fill_attribute_writes_the_requested_count() {
        let _ = ensure_console_stdin(); // guarantee a console exists first
        let stdout = open_console("CONOUT$")
            .expect("a console output buffer should be openable once a console exists");

        // SAFETY: `stdout` is a valid console output handle per the above.
        let written = unsafe { fill_attribute(stdout, 0x0007, 0, 0, 5) }
            .expect("FillConsoleOutputAttribute should succeed");
        assert_eq!(written, 5);
    }

    /// The empirical validation this whole primitive exists for: does a
    /// character synthesized via `write_char_events`, under the exact
    /// raw-mode recipe a real consumer (`rusty_lines`' Windows `term_sys`
    /// backend) applies, actually come back out of a `read` as the same
    /// byte(s) a real keypress would produce? This is the assumption every
    /// higher-level "drive a raw-mode reader with synthetic input" test
    /// depends on — proving it here, in isolation, means a failure here
    /// points straight at this primitive rather than masquerading as a
    /// mysterious failure three layers up in a consumer's own test suite.
    #[test]
    fn write_char_events_round_trips_through_raw_mode_read() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid console input handle.
        let original = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");
        let raw = (original & !(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT))
            | ENABLE_VIRTUAL_TERMINAL_INPUT
            | ENABLE_EXTENDED_FLAGS;
        // SAFETY: `stdin` is the same valid handle; `raw` is a plain
        // bitmask derived from a mode Windows itself just reported valid.
        unsafe { set_mode(stdin, raw) }.expect("SetConsoleMode should succeed");

        // A mix of an ordinary printable character and the ASCII control
        // character Ctrl-C maps to (`\x03`) — covers both "the console's
        // VT translation passes an ordinary char through as-is" and "an
        // ASCII control character round-trips as its own byte value",
        // which is specifically the case rush's Ctrl-C-at-idle-prompt
        // handling and the emacs keymap's Ctrl-bindings both depend on.
        let text = "a\x03";
        // SAFETY: `stdin` is the same valid, real console input handle.
        let written =
            unsafe { write_char_events(stdin, text) }.expect("WriteConsoleInputW should succeed");
        assert_eq!(
            written,
            (text.chars().count() * 2) as u32,
            "one down+up pair per char"
        );

        let mut buf = [0u8; 16];
        // SAFETY: `stdin` is the same valid handle; `buf` is a valid,
        // writable buffer.
        let n = unsafe { read(stdin, &mut buf) }.expect("ReadFile should succeed");
        assert_eq!(
            &buf[..n],
            text.as_bytes(),
            "raw-mode VT-input-mode read should return the same bytes a real keypress would"
        );

        // SAFETY: `stdin` is still the same valid handle; restoring the
        // original mode so this test doesn't leak state into others.
        unsafe { set_mode(stdin, original) }.expect("restoring the original mode should succeed");
    }

    /// The empirical validation `write_key_events` exists for: the left
    /// arrow key carries no `uChar` at all — exactly the case
    /// `write_char_events`'s own doc names as out of its scope — so this
    /// proves the virtual-key-code path round-trips through VT translation
    /// the same way `write_char_events_round_trips_through_raw_mode_read`
    /// already proves for character keys. `\x1b[D` is the standard VT100
    /// cursor-left sequence (ANSI/DEC-documented, not a Windows-specific
    /// guess) that every VT/ANSI-aware reader (including `rusty_lines`'
    /// own) already expects for a left-arrow keypress.
    #[test]
    fn write_key_events_left_arrow_round_trips_as_the_vt_escape_sequence() {
        let stdin = ensure_console_stdin();
        // SAFETY: `stdin` is a real, valid console input handle.
        let original = unsafe { get_mode(stdin) }.expect("GetConsoleMode should succeed");
        let raw = (original & !(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT))
            | ENABLE_VIRTUAL_TERMINAL_INPUT
            | ENABLE_EXTENDED_FLAGS;
        // SAFETY: `stdin` is the same valid handle; `raw` is a plain
        // bitmask derived from a mode Windows itself just reported valid.
        unsafe { set_mode(stdin, raw) }.expect("SetConsoleMode should succeed");

        // SAFETY: `stdin` is the same valid, real console input handle.
        let written = unsafe { write_key_events(stdin, VK_LEFT, 0) }
            .expect("WriteConsoleInputW should succeed");
        assert_eq!(written, 2, "one down+up pair for a single key");

        let mut buf = [0u8; 16];
        // SAFETY: `stdin` is the same valid handle; `buf` is a valid,
        // writable buffer.
        let n = unsafe { read(stdin, &mut buf) }.expect("ReadFile should succeed");
        assert_eq!(
            &buf[..n],
            b"\x1b[D",
            "left arrow should round-trip as the standard VT cursor-left escape sequence"
        );

        // SAFETY: `stdin` is still the same valid handle; restoring the
        // original mode so this test doesn't leak state into others.
        unsafe { set_mode(stdin, original) }.expect("restoring the original mode should succeed");
    }
}
