//! `SetConsoleCtrlHandler` — Windows' console-control-event mechanism, the
//! closest analog to `SIGINT`/`SIGTERM`/`SIGHUP` delivery for a console app.
//! Not a signal mask or `sigaction`-alike: handlers run on a dedicated
//! system-created thread, in one process-wide chain (`TRUE`/`FALSE` in
//! `SetConsoleCtrlHandler`'s second argument pushes/pops one entry), and
//! only `CTRL_C_EVENT`/`CTRL_BREAK_EVENT` are events a console app can
//! itself *generate*; `CTRL_CLOSE_EVENT`/`CTRL_LOGOFF_EVENT`/
//! `CTRL_SHUTDOWN_EVENT` are host-delivered shutdown notifications with no
//! Unix signal-number equivalent at all. See rush's
//! `docs/WINDOWS_BACKEND_ANALYSIS.md` §4.4 for the motivating case this
//! module exists for: a `trap 'cmd' TERM` that's silently accepted on
//! Windows today but has nothing installed to ever fire it.

use crate::error::Win32Error;

/// Ctrl+C, generated by the console driver (roughly `SIGINT`).
pub const CTRL_C_EVENT: u32 = 0;
/// Ctrl+Break — no Unix keystroke maps to this one.
pub const CTRL_BREAK_EVENT: u32 = 1;
/// The console window is closing (no exact Unix analog; closest in spirit
/// to `SIGHUP`).
pub const CTRL_CLOSE_EVENT: u32 = 2;
/// The current user is logging off (no Unix analog).
pub const CTRL_LOGOFF_EVENT: u32 = 5;
/// The system is shutting down (closest in spirit to `SIGTERM`).
pub const CTRL_SHUTDOWN_EVENT: u32 = 6;

/// A console control handler: called on a dedicated system thread with one
/// of the `CTRL_*_EVENT` constants above. Return nonzero (`TRUE`) to claim
/// the event — stopping it from propagating to the next handler in the
/// chain, or to the default handler, which terminates the process for every
/// event this module defines; return `0` (`FALSE`) to let it fall through.
///
/// `CTRL_CLOSE_EVENT`, `CTRL_LOGOFF_EVENT`, and `CTRL_SHUTDOWN_EVENT`
/// handlers get a bounded time budget before Windows kills the process
/// regardless (a few seconds) — keep the handler itself to the same "store
/// an atomic, do nothing else" pattern rush's own `trap::record_signal`
/// already uses for `SIGTERM`/`SIGHUP` on Unix, and let ordinary code pick
/// the stored value up at a safe point afterward.
pub type HandlerRoutine = extern "system" fn(ctrl_type: u32) -> i32;

#[link(name = "kernel32")]
unsafe extern "system" {
    fn SetConsoleCtrlHandler(handler_routine: Option<HandlerRoutine>, add: i32) -> i32;
}

/// Push `handler` onto the process-wide console-control-handler chain.
///
/// Handlers run last-installed-first; returning `FALSE` from `handler` lets
/// the call fall through to whatever was installed before it. Call
/// [`remove_ctrl_handler`] with the same function pointer to pop it back off
/// — installing the same `fn` item twice pushes two entries.
pub fn install_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: `handler` is a `'static` function pointer of the exact
    // signature `SetConsoleCtrlHandler` requires; `add = TRUE` (1) is a
    // plain flag, not a pointer.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 1) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

/// Pop `handler` off the console-control-handler chain. `handler` must be
/// the same function pointer previously passed to [`install_ctrl_handler`]
/// — Windows matches handlers by pointer identity, not by any handle this
/// module hands back.
pub fn remove_ctrl_handler(handler: HandlerRoutine) -> Result<(), Win32Error> {
    // SAFETY: see `install_ctrl_handler`; `add = FALSE` (0) removes rather
    // than adds.
    let ok = unsafe { SetConsoleCtrlHandler(Some(handler), 0) };
    if ok == 0 {
        Err(Win32Error::last())
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    extern "system" fn noop_handler(_ctrl_type: u32) -> i32 {
        0
    }

    #[test]
    fn install_then_remove_round_trips() {
        install_ctrl_handler(noop_handler).expect("install should succeed");
        remove_ctrl_handler(noop_handler).expect("remove should succeed");
    }

    #[test]
    fn removing_an_unregistered_handler_fails() {
        extern "system" fn never_installed(_ctrl_type: u32) -> i32 {
            0
        }
        assert!(remove_ctrl_handler(never_installed).is_err());
    }
}
